# Generated by Django 3.2.9 on 2021-11-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.CharField(default='dpt.jpg', max_length=100),
        ),
    ]
